[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Optimizer settings
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
  "@pythnetwork/=node_modules/@pythnetwork/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
